version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_username
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes: 
      - /data/db:/c/Users/z.ntchantchou/dev/JS/graphqlApiDb/db
      - /data/configdb:/c/Users/z.ntchantchou/dev/JS/graphqlApiDb/configdb
    ports:
      - 27017:27017