
"""dailyReport"""
type DailyReport {
  fips: Float
  provinceState: String
  countryRegion: String
  confirmed: Float
  deaths: Float
  recovered: Float
  active: Float
  createdAt: DateTime
  combinedKey: String
  lat: Float
  long: Float
  caseFatalityRatio: Float
  incidenceRate: Float
  iso: String
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

"""province"""
type Province {
  country: String!
  iso: String!
  population: String
  combinedKey: String!
  lat: String!
  long: String!
  provinceState: String!
}

"""country"""
type Country {
  country: String!
  iso: String!
  population: String
  combinedKey: String!
  lat: String!
  long: String!
  provinces: [Province!]!
}

"""user"""
type User {
  firstName: String!
  lastName: String!
  email: String!
  service: String!
  avatar: String!
  position: String!
}

type Query {
  getCountryReports(countryIso: String!, endDate: String, startDate: String): [DailyReport!]!
  getProvinceReports(countryIso: String!, province: String!, startDate: String, endDate: String): [DailyReport!]!
  getCountries: [Country!]!
  getCountry(iso: String!): Country!
  getUser: User!
}
